spring.application.name=unimed-test
spring.mvc.problemdetails.enabled=true
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=iso
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
